CREATE DATABASE sentinelai;

USE sentinelai;

CREATE TABLE tipos_incidente (
    id_tipo INT PRIMARY KEY AUTO_INCREMENT,
    nome_tipo VARCHAR(100)
);

CREATE TABLE paises (
    id_pais INT PRIMARY KEY AUTO_INCREMENT,
    nome_pais VARCHAR(100)
);

CREATE TABLE severidades (
    id_severidade INT PRIMARY KEY AUTO_INCREMENT,
    nivel VARCHAR(50)
);

USE sentinelai;

ALTER TABLE incidentes 
MODIFY COLUMN `DATA` TEXT CHARACTER SET latin1,
MODIFY COLUMN `TIPO INCIDENTE` TEXT CHARACTER SET latin1,
MODIFY COLUMN `SEVERIDADE` TEXT CHARACTER SET latin1,
MODIFY COLUMN `ORIGEM` TEXT CHARACTER SET latin1,
MODIFY COLUMN `STATUS` TEXT CHARACTER SET latin1,
MODIFY COLUMN `PAIS_ATAQUE` TEXT CHARACTER SET latin1,
MODIFY COLUMN `CLIENTE` TEXT CHARACTER SET latin1,
MODIFY COLUMN `NIVEL_AMEACA` TEXT CHARACTER SET latin1,
MODIFY COLUMN `RISCO_FINANCEIRO` TEXT CHARACTER SET latin1,
MODIFY COLUMN `IP_SUSPEITO` TEXT CHARACTER SET latin1,
MODIFY COLUMN `BLOQUEADO_AUTOMATICAMENTE` TEXT CHARACTER SET latin1,
MODIFY COLUMN `ATAQUE_REAL` TEXT CHARACTER SET latin1;

ALTER TABLE incidentes 
MODIFY COLUMN `DATA` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
MODIFY COLUMN `TIPO INCIDENTE` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
MODIFY COLUMN `SEVERIDADE` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
MODIFY COLUMN `ORIGEM` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
MODIFY COLUMN `STATUS` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
MODIFY COLUMN `PAIS_ATAQUE` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
MODIFY COLUMN `CLIENTE` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
MODIFY COLUMN `NIVEL_AMEACA` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
MODIFY COLUMN `RISCO_FINANCEIRO` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
MODIFY COLUMN `IP_SUSPEITO` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
MODIFY COLUMN `BLOQUEADO_AUTOMATICAMENTE` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
MODIFY COLUMN `ATAQUE_REAL` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

SELECT * FROM incidentes LIMIT 10;

SELECT * FROM incidentes LIMIT 10;

SHOW VARIABLES LIKE 'character_set%';

SET NAMES latin1;
SELECT * FROM incidentes LIMIT 10;

SHOW COLUMNS FROM incidentes;

ALTER TABLE incidentes CHANGE `ï»¿ID` ID INT;

SHOW DATABASES;

DESCRIBE incidentes;

SELECT * FROM incidentes LIMIT 10;
